//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.ServicioUCA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sistemas", Namespace="http://schemas.datacontract.org/2004/07/UCA.Servicios")]
    [System.SerializableAttribute()]
    public partial class Sistemas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlSistemaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSistema {
            get {
                return this.IdSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSistemaField, value) != true)) {
                    this.IdSistemaField = value;
                    this.RaisePropertyChanged("IdSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sistema {
            get {
                return this.SistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaField, value) != true)) {
                    this.SistemaField = value;
                    this.RaisePropertyChanged("Sistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlSistema {
            get {
                return this.UrlSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlSistemaField, value) != true)) {
                    this.UrlSistemaField = value;
                    this.RaisePropertyChanged("UrlSistema");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioPermisos", Namespace="http://schemas.datacontract.org/2004/07/UCA.Servicios")]
    [System.SerializableAttribute()]
    public partial class UsuarioPermisos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_cajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumInssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Negocio.ServicioUCA.Opciones[] OpcionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_caja {
            get {
                return this.C_cajaField;
            }
            set {
                if ((object.ReferenceEquals(this.C_cajaField, value) != true)) {
                    this.C_cajaField = value;
                    this.RaisePropertyChanged("C_caja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_costo {
            get {
                return this.C_costoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_costoField, value) != true)) {
                    this.C_costoField = value;
                    this.RaisePropertyChanged("C_costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumInss {
            get {
                return this.NumInssField;
            }
            set {
                if ((object.ReferenceEquals(this.NumInssField, value) != true)) {
                    this.NumInssField = value;
                    this.RaisePropertyChanged("NumInss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Negocio.ServicioUCA.Opciones[] Opciones {
            get {
                return this.OpcionesField;
            }
            set {
                if ((object.ReferenceEquals(this.OpcionesField, value) != true)) {
                    this.OpcionesField = value;
                    this.RaisePropertyChanged("Opciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opciones", Namespace="http://schemas.datacontract.org/2004/07/UCA.Servicios")]
    [System.SerializableAttribute()]
    public partial class Opciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdOpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlOpcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdOpcion {
            get {
                return this.IdOpcionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdOpcionField, value) != true)) {
                    this.IdOpcionField = value;
                    this.RaisePropertyChanged("IdOpcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Menu {
            get {
                return this.MenuField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuField, value) != true)) {
                    this.MenuField = value;
                    this.RaisePropertyChanged("Menu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nivel {
            get {
                return this.NivelField;
            }
            set {
                if ((object.ReferenceEquals(this.NivelField, value) != true)) {
                    this.NivelField = value;
                    this.RaisePropertyChanged("Nivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlOpcion {
            get {
                return this.UrlOpcionField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlOpcionField, value) != true)) {
                    this.UrlOpcionField = value;
                    this.RaisePropertyChanged("UrlOpcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subordinados", Namespace="http://schemas.datacontract.org/2004/07/UCA.Servicios")]
    [System.SerializableAttribute()]
    public partial class Subordinados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Inss_subordinadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_costo {
            get {
                return this.C_costoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_costoField, value) != true)) {
                    this.C_costoField = value;
                    this.RaisePropertyChanged("C_costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inss_subordinado {
            get {
                return this.Inss_subordinadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Inss_subordinadoField, value) != true)) {
                    this.Inss_subordinadoField = value;
                    this.RaisePropertyChanged("Inss_subordinado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosJefe", Namespace="http://schemas.datacontract.org/2004/07/UCA.Servicios")]
    [System.SerializableAttribute()]
    public partial class DatosJefe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centro_costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string centro_costo {
            get {
                return this.centro_costoField;
            }
            set {
                if ((object.ReferenceEquals(this.centro_costoField, value) != true)) {
                    this.centro_costoField = value;
                    this.RaisePropertyChanged("centro_costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OPS_request", Namespace="http://schemas.datacontract.org/2004/07/UCA.Servicios")]
    [System.SerializableAttribute()]
    public partial class OPS_request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_estructuraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_servicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string periodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_estructura {
            get {
                return this.c_estructuraField;
            }
            set {
                if ((object.ReferenceEquals(this.c_estructuraField, value) != true)) {
                    this.c_estructuraField = value;
                    this.RaisePropertyChanged("c_estructura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_servicio {
            get {
                return this.c_servicioField;
            }
            set {
                if ((object.ReferenceEquals(this.c_servicioField, value) != true)) {
                    this.c_servicioField = value;
                    this.RaisePropertyChanged("c_servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carnet {
            get {
                return this.carnetField;
            }
            set {
                if ((object.ReferenceEquals(this.carnetField, value) != true)) {
                    this.carnetField = value;
                    this.RaisePropertyChanged("carnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string periodo {
            get {
                return this.periodoField;
            }
            set {
                if ((object.ReferenceEquals(this.periodoField, value) != true)) {
                    this.periodoField = value;
                    this.RaisePropertyChanged("periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OPS_response", Namespace="http://schemas.datacontract.org/2004/07/UCA.Servicios")]
    [System.SerializableAttribute()]
    public partial class OPS_response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numero_opsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero_ops {
            get {
                return this.numero_opsField;
            }
            set {
                if ((object.ReferenceEquals(this.numero_opsField, value) != true)) {
                    this.numero_opsField = value;
                    this.RaisePropertyChanged("numero_ops");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datos_OPS", Namespace="http://schemas.datacontract.org/2004/07/UCA.Servicios")]
    [System.SerializableAttribute()]
    public partial class Datos_OPS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estructuraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_emisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numero_opsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string periodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string servicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estructura {
            get {
                return this.estructuraField;
            }
            set {
                if ((object.ReferenceEquals(this.estructuraField, value) != true)) {
                    this.estructuraField = value;
                    this.RaisePropertyChanged("estructura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha_emision {
            get {
                return this.fecha_emisionField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_emisionField, value) != true)) {
                    this.fecha_emisionField = value;
                    this.RaisePropertyChanged("fecha_emision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((object.ReferenceEquals(this.monedaField, value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string monto {
            get {
                return this.montoField;
            }
            set {
                if ((object.ReferenceEquals(this.montoField, value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero_ops {
            get {
                return this.numero_opsField;
            }
            set {
                if ((object.ReferenceEquals(this.numero_opsField, value) != true)) {
                    this.numero_opsField = value;
                    this.RaisePropertyChanged("numero_ops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string periodo {
            get {
                return this.periodoField;
            }
            set {
                if ((object.ReferenceEquals(this.periodoField, value) != true)) {
                    this.periodoField = value;
                    this.RaisePropertyChanged("periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                if ((object.ReferenceEquals(this.servicioField, value) != true)) {
                    this.servicioField = value;
                    this.RaisePropertyChanged("servicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUCA.IServiciosUca")]
    public interface IServiciosUca {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ValidarUsuario", ReplyAction="http://tempuri.org/IServiciosUca/ValidarUsuarioResponse")]
        Negocio.ServicioUCA.Sistemas[] ValidarUsuario(string Login, string Clave, string IpConexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ValidarUsuario", ReplyAction="http://tempuri.org/IServiciosUca/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<Negocio.ServicioUCA.Sistemas[]> ValidarUsuarioAsync(string Login, string Clave, string IpConexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ValidarPermisos", ReplyAction="http://tempuri.org/IServiciosUca/ValidarPermisosResponse")]
        Negocio.ServicioUCA.UsuarioPermisos ValidarPermisos(string userId, string sistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ValidarPermisos", ReplyAction="http://tempuri.org/IServiciosUca/ValidarPermisosResponse")]
        System.Threading.Tasks.Task<Negocio.ServicioUCA.UsuarioPermisos> ValidarPermisosAsync(string userId, string sistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ValidarCedula", ReplyAction="http://tempuri.org/IServiciosUca/ValidarCedulaResponse")]
        string ValidarCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ValidarCedula", ReplyAction="http://tempuri.org/IServiciosUca/ValidarCedulaResponse")]
        System.Threading.Tasks.Task<string> ValidarCedulaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/EliminarRegistroSesion", ReplyAction="http://tempuri.org/IServiciosUca/EliminarRegistroSesionResponse")]
        string EliminarRegistroSesion(string IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/EliminarRegistroSesion", ReplyAction="http://tempuri.org/IServiciosUca/EliminarRegistroSesionResponse")]
        System.Threading.Tasks.Task<string> EliminarRegistroSesionAsync(string IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ConsultaSubordinados", ReplyAction="http://tempuri.org/IServiciosUca/ConsultaSubordinadosResponse")]
        Negocio.ServicioUCA.Subordinados[] ConsultaSubordinados(string inss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ConsultaSubordinados", ReplyAction="http://tempuri.org/IServiciosUca/ConsultaSubordinadosResponse")]
        System.Threading.Tasks.Task<Negocio.ServicioUCA.Subordinados[]> ConsultaSubordinadosAsync(string inss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ConsultaJefe", ReplyAction="http://tempuri.org/IServiciosUca/ConsultaJefeResponse")]
        Negocio.ServicioUCA.DatosJefe ConsultaJefe(string inss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/ConsultaJefe", ReplyAction="http://tempuri.org/IServiciosUca/ConsultaJefeResponse")]
        System.Threading.Tasks.Task<Negocio.ServicioUCA.DatosJefe> ConsultaJefeAsync(string inss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/OPS_prematricula", ReplyAction="http://tempuri.org/IServiciosUca/OPS_prematriculaResponse")]
        Negocio.ServicioUCA.OPS_response OPS_prematricula(Negocio.ServicioUCA.OPS_request ops);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/OPS_prematricula", ReplyAction="http://tempuri.org/IServiciosUca/OPS_prematriculaResponse")]
        System.Threading.Tasks.Task<Negocio.ServicioUCA.OPS_response> OPS_prematriculaAsync(Negocio.ServicioUCA.OPS_request ops);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/Consulta_OPS", ReplyAction="http://tempuri.org/IServiciosUca/Consulta_OPSResponse")]
        Negocio.ServicioUCA.Datos_OPS Consulta_OPS(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/Consulta_OPS", ReplyAction="http://tempuri.org/IServiciosUca/Consulta_OPSResponse")]
        System.Threading.Tasks.Task<Negocio.ServicioUCA.Datos_OPS> Consulta_OPSAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/Consulta_OPS_Carnet", ReplyAction="http://tempuri.org/IServiciosUca/Consulta_OPS_CarnetResponse")]
        Negocio.ServicioUCA.Datos_OPS[] Consulta_OPS_Carnet(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosUca/Consulta_OPS_Carnet", ReplyAction="http://tempuri.org/IServiciosUca/Consulta_OPS_CarnetResponse")]
        System.Threading.Tasks.Task<Negocio.ServicioUCA.Datos_OPS[]> Consulta_OPS_CarnetAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosUcaChannel : Negocio.ServicioUCA.IServiciosUca, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosUcaClient : System.ServiceModel.ClientBase<Negocio.ServicioUCA.IServiciosUca>, Negocio.ServicioUCA.IServiciosUca {
        
        public ServiciosUcaClient() {
        }
        
        public ServiciosUcaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosUcaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosUcaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosUcaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Negocio.ServicioUCA.Sistemas[] ValidarUsuario(string Login, string Clave, string IpConexion) {
            return base.Channel.ValidarUsuario(Login, Clave, IpConexion);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServicioUCA.Sistemas[]> ValidarUsuarioAsync(string Login, string Clave, string IpConexion) {
            return base.Channel.ValidarUsuarioAsync(Login, Clave, IpConexion);
        }
        
        public Negocio.ServicioUCA.UsuarioPermisos ValidarPermisos(string userId, string sistId) {
            return base.Channel.ValidarPermisos(userId, sistId);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServicioUCA.UsuarioPermisos> ValidarPermisosAsync(string userId, string sistId) {
            return base.Channel.ValidarPermisosAsync(userId, sistId);
        }
        
        public string ValidarCedula(string cedula) {
            return base.Channel.ValidarCedula(cedula);
        }
        
        public System.Threading.Tasks.Task<string> ValidarCedulaAsync(string cedula) {
            return base.Channel.ValidarCedulaAsync(cedula);
        }
        
        public string EliminarRegistroSesion(string IdUsuario) {
            return base.Channel.EliminarRegistroSesion(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<string> EliminarRegistroSesionAsync(string IdUsuario) {
            return base.Channel.EliminarRegistroSesionAsync(IdUsuario);
        }
        
        public Negocio.ServicioUCA.Subordinados[] ConsultaSubordinados(string inss) {
            return base.Channel.ConsultaSubordinados(inss);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServicioUCA.Subordinados[]> ConsultaSubordinadosAsync(string inss) {
            return base.Channel.ConsultaSubordinadosAsync(inss);
        }
        
        public Negocio.ServicioUCA.DatosJefe ConsultaJefe(string inss) {
            return base.Channel.ConsultaJefe(inss);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServicioUCA.DatosJefe> ConsultaJefeAsync(string inss) {
            return base.Channel.ConsultaJefeAsync(inss);
        }
        
        public Negocio.ServicioUCA.OPS_response OPS_prematricula(Negocio.ServicioUCA.OPS_request ops) {
            return base.Channel.OPS_prematricula(ops);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServicioUCA.OPS_response> OPS_prematriculaAsync(Negocio.ServicioUCA.OPS_request ops) {
            return base.Channel.OPS_prematriculaAsync(ops);
        }
        
        public Negocio.ServicioUCA.Datos_OPS Consulta_OPS(string codigo) {
            return base.Channel.Consulta_OPS(codigo);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServicioUCA.Datos_OPS> Consulta_OPSAsync(string codigo) {
            return base.Channel.Consulta_OPSAsync(codigo);
        }
        
        public Negocio.ServicioUCA.Datos_OPS[] Consulta_OPS_Carnet(string codigo) {
            return base.Channel.Consulta_OPS_Carnet(codigo);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServicioUCA.Datos_OPS[]> Consulta_OPS_CarnetAsync(string codigo) {
            return base.Channel.Consulta_OPS_CarnetAsync(codigo);
        }
    }
}
